/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    Integer[] emptyArr;
    Sort<Integer> emptySort;
    Integer[] integerArr;
    Sort<Integer> integerSort;
    Integer[] integerNegArr;
    Sort<Integer> integerNegSort;

    @Before
    public void init(){
        emptyArr =  new Integer[0];
        emptySort = new Sort<>();
        integerArr = new Integer[]{4, 25, 30, 15, 16};
        integerSort = new Sort<>();
        integerNegArr = new Integer[]{4, -25, 30, 15, -15, 99, 3, 0};
        integerNegSort = new Sort<>();
    }

    @Test
    public void testInsertionSortEmpty() {
        assertArrayEquals(new Integer[]{}, emptySort.insertionSort(emptyArr));
    }

    @Test
    public void testInsertionSortMultNum() {
        assertArrayEquals(new Integer[]{4, 15, 16, 25, 30}, integerSort.insertionSort(integerArr));
    }

    @Test
    public void testInsertionSortNeg() {
        assertArrayEquals(new Integer[]{-25, -15, 0, 3, 4, 15, 30, 99},
                integerNegSort.insertionSort(integerNegArr));
    }

}
