/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import ArrayReverse.ArrayReverse;
import ArrayShift.ArrayShift;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {

    }
}
