/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort;

import java.util.Arrays;

public class App {



    public static void main(String[] args) {

        Integer[] integerNegArr = new Integer[] {8,4,23,42,16,15};

        Sort<Integer> integerNegSort = new Sort<>();

        System.out.println(Arrays.toString(
                integerNegSort.quicksort(integerNegArr, 0, (integerNegArr.length -1))
        ));
    }
}
