/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import types.BinarySearchTree;

public class App {

    private static final BinarySearchTree<Integer> binarySearchTree = new BinarySearchTree<>();

    public static void main(String[] args) {

        binarySearchTree.add(5);
        binarySearchTree.add(3);
        binarySearchTree.add(8);
        binarySearchTree.add(1);
        binarySearchTree.add(7);


    }
}
