/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.junit.Test;
import types.LinkedList;

import static org.junit.Assert.*;

public class AppTest {

    private LinkedList<String> list;

    @Test public void testLinkedListTrue(){
        list=new LinkedList<>();
        list.add("Mohammad");
        list.insert("Khaled");
        assertEquals(true, list.includes("Mohammad"));
    }

    @Test public void testLinkedListFalse(){
        list=new LinkedList<>();
        list.add("Rana");
        list.insert("Khaled");
        assertEquals(false, list.includes("Mohammad"));
    }

    @Test public void testLinkedListToString(){
        list = new LinkedList<>();
        list.add("Mohammad");
        list.add("Khaled");
        list.insert("Abu");
        list.insert("Mattar");
        assertEquals("{Mohammad}-> {Khaled}-> {Abu}-> {Mattar}-> NULL", list.toString());
    }
}
